---
title: "W1-Network-Stratified"
output: html_document
date: "2025-06-17"
---


```{r Load Packages}
packages <- c("tidyverse", "haven", "dplyr","igraph", "reshape2", "qgraph")
lapply(packages, function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg)
  }
  library(pkg, character.only = TRUE)
})
```


```{r Stratifying Data from Wave 1}
# Filter Alcohol Use Groups 
# Group 1: Mothers who responded with 2 or 3
alcohol_group <- subset(alcohol_use_data, g9 %in% c(2, 3))

#total number of participants of mothers who used alcohol during pregnancy is 1088

# Group 2: Mothers who responded with 1 or 8
no_alcohol_group <- subset(alcohol_use_data, g9 %in% c(1, 8))

#total number of participants of mothers who DO NOT report alcohol use during pregnancy is 13,913

#Merging Subsets with CBCL Data from Wave 1 
W1_cbcl_alcohol_use <- merge(alcohol_group, cbcl_wide_wave1, by = "folio")

# Merge group 1 or 8 with CBCL wide data
W1_cbcl_no_alcohol<- merge(no_alcohol_group, cbcl_wide_wave1, by = "folio")
```




```{r Network for Alcohol Use Group W1}

#Plotting Network using Lasso + Centrality Analysis from (Fritz et al, 2020)}

# Step 1 Create Correlation matrix (excluding 'folio')
symptom_data1S <- W1_cbcl_alcohol_use  %>% select(-folio, -g9) #filtering participant ID 
symptom_corr1S <- cor(symptom_data1S, use = "pairwise.complete.obs") # cor function computes the correlation between columns x and y,  "pairwise.complete.obscomputes each pairwise correlation using only the rows (observations) that have non-missing values for that pair of variables

# Step 2 Apply graphical lasso using qgraph
# This automatically estimates a regularized partial correlation network
symptom_glasso1S<- qgraph(
  symptom_corr1S,
  graph = "glasso",#obtain an optimal sparse estimate of the partial correlation matrix using the glasso package (Friedman, Hastie and Tibshirani, 2011)
  sampleSize = nrow(symptom_data1S),
  layout = "spring",  # "spring" gives a force embedded layout, other options are "circle" or "groups", in fritz paper she used "layout"
  details = TRUE,
  minimum = 0.1,      # filter edges below this value not sure if we should filter for a maximum too 
  edge.color = "skyblue",
  edge.width = 1,     # qgraph auto scales edge widths
  nodeNames = colnames(symptom_corr1S),
  theme = "Hollywood",
  fade = FALSE,
  label.cex = 1.1,
  legend = TRUE,
  legend.cex= 0.5,
  main = "CBCL Symptom Network Alcohol Use Group (Graphical Lasso, r > 0.4)"
)

#Centrality Measure Analysis 
#Output table gives: betweenness centrality, closeness, strength, expected influence, shortest path length 
W1S_Centrality <- centrality_auto(symptom_glasso)
print(W1S_Centrality)
```


```

